FROM python:3.10-slim-buster

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy the entire application code
COPY . .

# Expose the port Flask will run on
EXPOSE 5000

# Set environment variables
ENV FLASK_APP=app

# Start the Flask server
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]